# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'SDCycleScrollView', '~> 1.65'
target '最后一个项目' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 最后一个项目

  target '最后一个项目Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '最后一个项目UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
